import './globals.css'
import { Inter } from 'next/font/google'

//components
import Navbar from './components/UpperNavbar'
import NavMenu from './components/Navmenu'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <NavMenu/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}